---
title: "The breakdown of communication products"
author: "PA"
date: today
format: html
---

Assignment 1: Breaking down articles

## Articles analysis

### Print media: https://theconversation.com/australians-say-ai-shouldnt-produce-political-news-but-its-ok-for-sport-new-research-231369

#### Summary
Aiming to reflect the impacts of the growing occupation of artificial intelligence, the article represents how audiences respond to various types of journalism generated by AI products. The results indicated that viewers' trust towards the concerns varied among different genres and significantly relied on how much they were aware and understanding of AI technologies. Thus, the authors suggested that to enhance the adoption of AI tools, organizations should publish the authority and production of the news origin, gaining the audience’s credibility. 

#### Sections
Background

The news article focuses on the context of emerging AI tools in generating news to improve productivity, creativity, and efficiency. The Digital News Report conducted an online survey of more than 2000 Australians to collect the audience’s interaction regarding the utilization of artificial intelligence in producing various news topics. The authors have created a comprehensive and informative background at the beginning of the article to attract viewers. 

Lede 

The article's first paragraph contained a short sentence stating the interesting finding regarding how Australians interact with news produced by humans or AI. Specifically, the article authors, Caroline, Kieran, and Sora, wrote: 

> “This year’s Digital News Report: Australia 2024 finds Australians prefer news that is made by humans rather than AI, but the degree of discomfort depends on the topic.”

Summary

After specifying the survey results, the authors summarized the different credibility levels of the audience regarding the utilization of AI assistance in generating various news topics.  

> “This suggests those who favour so-called “hard” news subjects are more sceptical about the use of AI in news and the impact it might have on the quality of news about important civic and social issues. Sports, lifestyle and culture news lovers are more relaxed about it, reflecting the different role these news genres play in people’s lives”


Main results 

The article concludes that the significant elements of how the audience interacts with the adoption of AI in creating news depend on the credibility of the news source and the awareness of generative tools. This was mainly stated in the last section: **People who trust news are more comfortable with AI**. Following that, the author also gave suggestions to the media organizations, attempting to emphasize the audiences’ demand and 

### Blog post: https://blog.pragmaticengineer.com/how-does-chatgpt-work/
#### Summary
The article provides an explanation of how ChatGPT, one of the most potential products of OpenAI, operates to interact with users’ requests. The responding process consists of several steps, starting with analyzing the inputs, breaking the sentences into tokens, followed by generating embedding to finalize predicting results keywords. The two pretraining and inference procedures are also involved in the process of repeating the word input evaluation and prediction based on the equivalent algorithm. Opposite to the human-like feature, the basic concept of ChatGPT mainly relies on computing techniques using human-created samples to produce comprehensive texts and results. 

#### Sections
Background

The background was given under the author's first question to the engineering team, introducing the development of ChatGPT and its applied technologies and operation systems. The general introduction to this artificial intelligence industry and a brief description of the engineering team provide interesting relevance and credibility of the following content to the audience. 


Lede 
The lede was itself the title of the blog post, indicating the main contents of the article and highlighting the involvement of the technology experts’ team. 


Summary
The author includes a quote from Wolfamalpha’s founder in the last paragraph of the blog post to summarise ChatGPT's operation process. The summary was given by an expert, providing the reader with a professional and comprehensive explanation of the myths of AI products. 


Main results
The blog post's significant finding indicates that although ChatGPT and other generative AI tools seem to operate impressively to replace humans, their work is actually based on simulation and computing techniques. 

> “For a sense of ChatGPT’s limitations, you need to understand how it works. ChatGPT and other LLMs do not “think” and “understand” like humans. ChatGPT does, however, generate words based on what the next most likely word should be, looking at the input, and everything generated so far.”

### Video: https://www.youtube.com/watch?v=iqUFERBJwoY
#### Summary

#### Sections
Background
At the beginning of the video, the presenter showed a graph comparing Australian disposable income and housing prices in the last 30 years, illustrating the context of rising house prices causing controversial impacts. Presenting data to introduce the concern provides the real current situation with clear information, capturing the audience’s attention. 


Lede
Right after the video's context, Matilda—the speaker—raised the main concern: **There's a lot of debate about how and why Australia's housing market became the garbage fire that it is today, and accusations are often directed at one particular suspect of negative gearing** (from 0:27 to 0:38). 


Summary
The summary of the story followed the explanation about negative gearing, which develops the cause of capital gains tax. The whole explanation from 2:02 to 2:54 specifies the other controversial aspect of the story’s concern, providing the audience with a deep and combined process of how 


Main result
The story concluded the debated concern with a combined graph of three indexes and the statement from Matilda: **When it comes to the country's housing crisis, negative gearing is just the garbage, which needed a lit match to set it alight** (from 3:48 to 4:00). 
